#!/bin/bash
set -e

CERTS_DIR="src/main/resources/certs"
OFB_CERTS_DIR="ofb-mock-server/src/main/resources/certs"

mkdir -p "$CERTS_DIR"

echo "Copying mTLS certificates from OFB mock server..."

# Copy client keystore (generated by OFB mock server)
cp "$OFB_CERTS_DIR/client.p12" "$CERTS_DIR/client.p12"

# Copy OFB server certificate for trust
cp "$OFB_CERTS_DIR/server.cer" "$CERTS_DIR/server.cer"

echo "Certificates copied successfully to $CERTS_DIR/"
echo "  - client.p12: Client keystore (for mTLS authentication)"
echo "  - server.cer: OFB server certificate (for trust)"
